ark:
  container_name: ark
  image: knowonehome/ark-server-host
  environment:
    - SESSIONNAME=Ark Docker
    - SERVERMAP=TheIsland
    - SERVERPASSWORD=""
    - ADMINPASSWORD=adminpassword
    - SERVERPORT=7777
    - QUERYPORT=27015
    - BACKUPONSTART=1
    - BACKUPONSTOP=1
    - WARNONSTOP=1
    - UPDATEONSTART=1
    - TZ=America/Chicago
    - GID=1000
    - UID=1000
  volumes:
    - /my/path/to/ark:/ark
  ports:
   - 7777:7777/udp
   - 7777:7777
   - 27015:27015/udp
   - 27015:27015
   - 32330:32330
